# Generated by Django 3.0.3 on 2020-03-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_application_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sex',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(upload_to='media/'),
        ),
    ]
