# Generated by Django 3.0.3 on 2020-03-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200306_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='sex',
            field=models.CharField(max_length=8),
        ),
    ]
