# Generated by Django 3.0.3 on 2020-03-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20200306_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.CharField(max_length=2),
        ),
    ]
