# Generated by Django 3.0.3 on 2020-03-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20200306_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='age',
            new_name='ages',
        ),
    ]
