# Generated by Django 3.0.3 on 2020-03-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200306_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='ages',
        ),
    ]
