# Generated by Django 3.0.3 on 2020-03-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_remove_application_ages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='sex',
        ),
    ]
